### ISSUE TITLE
Crash related to DB version

### ISSUE THREAD

**Issue by mayankkrjain** [yigit/android-priority-jobqueue#220]
Hi,
We are facing crashes in our android application related to this library. The play-store version of the app used the older path/job-queue library (1.1.2) . We upgraded the version to use yirgit/job-queue (2.0.0-alpha5) . But sometimes when we try to upgrade the app from playstore-version to latest one , we see this crash. This is device independent.Could it be something wrong  with our usage of this library ?

`07-28 10:49:25.186 29626-29626/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   java.lang.RuntimeException: Unable to create application android.database.sqlite.SQLiteException: Can't downgrade database from version 11 to 3
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6320)
                                                       at android.app.ActivityThread.access$1800(ActivityThread.java:221)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1860)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:158)
                                                       at android.app.ActivityThread.main(ActivityThread.java:7225)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
                                                    Caused by: android.database.sqlite.SQLiteException: Can't downgrade database from version 11 to 3
                                                       at android.database.sqlite.SQLiteOpenHelper.onDowngrade(SQLiteOpenHelper.java:360)
                                                       at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:254)
                                                       at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
                                                       at com.path.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue.<init>(SqliteJobQueue.java:42)
                                                       at com.path.android.jobqueue.JobManager$DefaultQueueFactory.createPersistentQueue(JobManager.java:594)
                                                       at com.path.android.jobqueue.JobManager.<init>(JobManager.java:77)
                                                       at com.path.android.jobqueue.JobManager.<init>(JobManager.java:61)`

**Comment by yigit** [comment]
The exception looks like someone is trying to install the play store (path) version on top of the new version, which won't work. I'm confused, did you not release the new version using `v2.0` to the play store ?

**Comment by mayankkrjain** [comment]
We got the proper feedback from the testers who were reporting this issue.
They were doing exactly what you mentioned, which is incorrect.
We would be releasing v2. 0 to playstore this week.  I am closing this
issue as its resolved.  Thanks.

**Comment by yigit** [comment]
cool :). Btw move to beta2 if you can before releasing.

**Comment by mayankkrjain** [comment]
Is beta2 release stable?

**Comment by mayankkrjain** [comment]
BTW , We got this crash report as well. Copying it here just in case this is of any relevance. 
`Crash Logs :
java.lang.RuntimeException: cannot save job to disk
	at com.birbit.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue.persistJobToDisk(SqliteJobQueue.java:103)
	at com.birbit.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue.insert(SqliteJobQueue.java:86)
	at com.birbit.android.jobqueue.cachedQueue.CachedJobQueue.insert(CachedJobQueue.java:29)
	at com.birbit.android.jobqueue.JobManagerThread.handleAddJob(JobManagerThread.java:141)
	at com.birbit.android.jobqueue.JobManagerThread.access$000(JobManagerThread.java:35)
	at com.birbit.android.jobqueue.JobManagerThread$1.handleMessage(JobManagerThread.java:225)
	at com.birbit.android.jobqueue.messaging.PriorityMessageQueue.consume(PriorityMessageQueue.java:39)
	at com.birbit.android.jobqueue.JobManagerThread.run(JobManagerThread.java:220)
	at java.lang.Thread.run(Thread.java:818)
Caused by: java.io.FileNotFoundException: /data/data/*LOCATION*/app_com_birbit_jobqueue_jobs/files_jobs_AnalyticsJobManager/db5652f3-2c65-4e0b-b7c3-fd7731c7f69e.jobs: open failed: ENOENT (No such file or directory)
	at libcore.io.IoBridge.open(IoBridge.java:456)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:87)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:72)
	at okio.Okio.sink(Okio.java:181)
	at com.birbit.android.jobqueue.persistentQueue.sqlite.FileStorage.save(FileStorage.java:57)
	at com.birbit.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue.persistJobToDisk(SqliteJobQueue.java:101)`

**Comment by yigit** [comment]
Did you redact the package name from the logs or does it really have *LOCATION* in the path?

**Comment by mayankkrjain** [comment]
I redacted it :)






*Regards,Mayank JainIIIT-H,
Hyderabadhttp://www.linkedin.com/in/mayankkrjain
<http://www.linkedin.com/in/mayankkrjain>+91-7799144432*

**Comment by yigit** [comment]
Hmm, that one is scary. Is there any steps to reproduce it?

Also, yes beta2 is more stable and from betaX to version, job manager will be backward compatible with jobs created in previous beta+ versions.

**Comment by mayankkrjain** [comment]
In the application there is an offline-workflow scenario , wherein Data is
stored offline in the cache. User has an option to clear this cache. It
seems on clearing, the file/db is getting deleted causing the run-time
exception. Can we do something here? Re-creating the file/DB if it's not
there instead of throwing a run-time exception. We don't care if lose all
the stored job-data.






*Regards,Mayank JainIIIT-H,
Hyderabadhttp://www.linkedin.com/in/mayankkrjain
<http://www.linkedin.com/in/mayankkrjain>+91-7799144432*

**Comment by yigit** [comment]
If user deletes data from system menu, Android would restart the app. If
your app is deleting the data, why don't you just leave job folder as is
and instead cancel all jobs?
You can just give all jobs the same tag and cancel all using that tag?

**Comment by yigit** [comment]
Ugh this sucks. What client is doing is definitely wrong though :/. If you don't persist jobs, you'll be losing the information. I can change `FileStorage` to make sure parent directory exists before writing a file which should cover most of the cases. There will still be a race condition if user deletes the data right after folder is created but before file is written but that might be a good enough compromise.

**Comment by yigit** [comment]
Actually, even if I change the FileStorage, if they delete database file, that is hard to recover from. We'll have an open connection to the database file though so idk what the OS will do if they try to delete a file in use. Need to experiment with it.

**Comment by yigit** [comment]
Sorry but I'm going to mark it as infeasible because JobManager cannot reliably handle any case that includes removing its files. 
There is a lot of cases like open database connections that are hard to recover from if the underlying file is lost and in a realistic case, this would only happen if the device is broken.

Anybody using your library should respect its files :/.

**Comment by mayankkrjain** [comment]
That's OK.  We understand this.  We have communicated the same to our
clients and discussions related to this are in progress.
Till then,  we are not persisting the jobs.  Hopefully this will get
resolved soon on our end.
Thanks.

**Comment by yigit** [comment]
thanks!

**Comment by TasneemBohra** [comment]
I am still getting this issue 

`java.lang.RuntimeException: An error occurred while executing doInBackground()
07-18 06:48:36.458 10193 10216 E AndroidRuntime: 	at android.os.AsyncTask$3.done(AsyncTask.java:309)
07-18 06:48:36.458 10193 10216 E AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
07-18 06:48:36.458 10193 10216 E AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
07-18 06:48:36.458 10193 10216 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
07-18 06:48:36.458 10193 10216 E AndroidRuntime: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
07-18 06:48:36.458 10193 10216 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
07-18 06:48:36.458 10193 10216 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
07-18 06:48:36.458 10193 10216 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:818)
07-18 06:48:36.458 10193 10216 E AndroidRuntime: Caused by: android.database.sqlite.SQLiteException: Can't downgrade database from version 12 to 3
07-18 06:48:36.458 10193 10216 E AndroidRuntime: 	at android.database.sqlite.SQLiteOpenHelper.onDowngrade(SQLiteOpenHelper.java:360)
07-18 06:48:36.458 10193 10216 E AndroidRuntime: 	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:254)
07-18 06:48:36.458 10193 10216 E AndroidRuntime: 	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:163)
07-18 06:48:36.458 10193 10216 E AndroidRuntime: 	at com.path.android.jobqueue.persistentQueue.sqlite.SqliteJobQueue.<init>(SqliteJobQueue.java:42)
07-18 06:48:36.458 10193 10216 E AndroidRuntime: 	at com.path.android.jobqueue.JobManager$DefaultQueueFactory.createPersistentQueue(JobManager.java:594)
07-18 06:48:36.458 10193 10216 E AndroidRuntime: 	at com.path.android.jobqueue.JobManager.<init>(JobManager.java:77)`
